version: 2

models:
  - name: fct_stock_valuation
    description: "Bảng tổng hợp thông tin định giá và giá đóng cửa của cổ phiếu"
    columns:
      - name: ticker
        description: "Mã cổ phiếu"
        tests:
          - not_null
      - name: trading_date
        description: "Ngày giao dịch"
        tests:
          - not_null

  - name: dim_market_sentiment
    description: "Bảng chiều xu hướng sắc thái tin tức thị trường theo từng ngày"
    columns:
      - name: ticker
        description: "Mã cổ phiếu"
        tests:
          - not_null
      - name: sentiment_date
        description: "Ngày ghi nhận tin tức"
        tests:
          - not_null
