apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dagster-slack-api-token
  namespace: dagster
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dagster-slack-api-token
    creationPolicy: Owner
  data:
    - secretKey: SLACK_API_TOKEN
      remoteRef:
        key: finops-db-credentials
        property: slack_api_token
    - secretKey: token
      remoteRef:
        key: finops-db-credentials
        property: slack_api_token
