{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'TRADING_DATE'],
    incremental_strategy='merge'
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  TRADING_DATE::DATE AS TRADING_DATE,
  OPEN::NUMERIC(18, 4) AS OPEN,
  HIGH::NUMERIC(18, 4) AS HIGH,
  LOW::NUMERIC(18, 4) AS LOW,
  CLOSE::NUMERIC(18, 4) AS CLOSE,
  VOLUME::NUMERIC(18, 4) AS VOLUME,
  VALUE::NUMERIC(18, 4) AS VALUE,
  ADJUSTED_CLOSE::NUMERIC(18, 4) AS ADJUSTED_CLOSE,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_STOCK_PRICE_EOD') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
