{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'PERIOD', 'YEAR'],
    incremental_strategy='merge',
    merge_exclude_columns=['DATACORE_CREATE_DATETIME', 'DATACORE_CREATE_PROGRAM', 'DATACORE_CREATE_BY']
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  PERIOD::VARCHAR(256) AS PERIOD,
  YEAR::INTEGER AS YEAR,
  REVENUE::NUMERIC(18, 4) AS REVENUE,
  COGS::NUMERIC(18, 4) AS COGS,
  GROSS_PROFIT::NUMERIC(18, 4) AS GROSS_PROFIT,
  OPERATING_EXPENSES::NUMERIC(18, 4) AS OPERATING_EXPENSES,
  OPERATING_PROFIT::NUMERIC(18, 4) AS OPERATING_PROFIT,
  FINANCIAL_INCOME::NUMERIC(18, 4) AS FINANCIAL_INCOME,
  FINANCIAL_EXPENSES::NUMERIC(18, 4) AS FINANCIAL_EXPENSES,
  NET_PROFIT_AFTER_TAX::NUMERIC(18, 4) AS NET_PROFIT_AFTER_TAX,
  {{ datacore_common_metadata() }}
FROM {{ source('RAW', 'RAW_INCOME_STATEMENT') }}
{% if is_incremental() %}
  -- Filter by partition key for incremental run
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
