{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'PERIOD', 'YEAR'],
    incremental_strategy='merge',
    merge_exclude_columns=['DATACORE_CREATE_DATETIME', 'DATACORE_CREATE_PROGRAM', 'DATACORE_CREATE_BY']
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  PERIOD::VARCHAR(256) AS PERIOD,
  YEAR::INTEGER AS YEAR,
  NULLIF(NULLIF(LOWER(REVENUE), 'nan'), '')::NUMERIC(38, 4) AS REVENUE,
  NULLIF(NULLIF(LOWER(COGS), 'nan'), '')::NUMERIC(38, 4) AS COGS,
  NULLIF(NULLIF(LOWER(GROSS_PROFIT), 'nan'), '')::NUMERIC(38, 4) AS GROSS_PROFIT,
  NULLIF(NULLIF(LOWER(OPERATING_EXPENSES), 'nan'), '')::NUMERIC(38, 4) AS OPERATING_EXPENSES,
  NULLIF(NULLIF(LOWER(OPERATING_PROFIT), 'nan'), '')::NUMERIC(38, 4) AS OPERATING_PROFIT,
  NULLIF(NULLIF(LOWER(FINANCIAL_INCOME), 'nan'), '')::NUMERIC(38, 4) AS FINANCIAL_INCOME,
  NULLIF(NULLIF(LOWER(FINANCIAL_EXPENSES), 'nan'), '')::NUMERIC(38, 4) AS FINANCIAL_EXPENSES,
  NULLIF(NULLIF(LOWER(NET_PROFIT_AFTER_TAX), 'nan'), '')::NUMERIC(38, 4) AS NET_PROFIT_AFTER_TAX,
  {{ datacore_common_metadata() }}
FROM {{ latest_source(source("RAW", "RAW_INCOME_STATEMENT"), ['TICKER','PERIOD','YEAR']) }}
