{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'PERIOD', 'YEAR'],
    incremental_strategy='merge'
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  PERIOD::VARCHAR(256) AS PERIOD,
  YEAR::INTEGER AS YEAR,
  TOTAL_ASSETS::NUMERIC(18, 4) AS TOTAL_ASSETS,
  CURRENT_ASSETS::NUMERIC(18, 4) AS CURRENT_ASSETS,
  CASH::NUMERIC(18, 4) AS CASH,
  INVENTORY::NUMERIC(18, 4) AS INVENTORY,
  TOTAL_LIABILITIES::NUMERIC(18, 4) AS TOTAL_LIABILITIES,
  SHORT_TERM_DEBT::NUMERIC(18, 4) AS SHORT_TERM_DEBT,
  LONG_TERM_DEBT::NUMERIC(18, 4) AS LONG_TERM_DEBT,
  EQUITY::NUMERIC(18, 4) AS EQUITY,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_BALANCE_SHEET') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
