{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'PERIOD', 'YEAR'],
    incremental_strategy='merge',
    merge_exclude_columns=['DATACORE_CREATE_DATETIME', 'DATACORE_CREATE_PROGRAM', 'DATACORE_CREATE_BY']
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  PERIOD::VARCHAR(256) AS PERIOD,
  YEAR::INTEGER AS YEAR,
  NULLIF(NULLIF(LOWER(TOTAL_ASSETS), 'nan'), '')::NUMERIC(38, 4) AS TOTAL_ASSETS,
  NULLIF(NULLIF(LOWER(CURRENT_ASSETS), 'nan'), '')::NUMERIC(38, 4) AS CURRENT_ASSETS,
  NULLIF(NULLIF(LOWER(CASH), 'nan'), '')::NUMERIC(38, 4) AS CASH,
  NULLIF(NULLIF(LOWER(INVENTORY), 'nan'), '')::NUMERIC(38, 4) AS INVENTORY,
  NULLIF(NULLIF(LOWER(TOTAL_LIABILITIES), 'nan'), '')::NUMERIC(38, 4) AS TOTAL_LIABILITIES,
  NULLIF(NULLIF(LOWER(SHORT_TERM_DEBT), 'nan'), '')::NUMERIC(38, 4) AS SHORT_TERM_DEBT,
  NULLIF(NULLIF(LOWER(LONG_TERM_DEBT), 'nan'), '')::NUMERIC(38, 4) AS LONG_TERM_DEBT,
  NULLIF(NULLIF(LOWER(EQUITY), 'nan'), '')::NUMERIC(38, 4) AS EQUITY,
  {{ datacore_common_metadata() }}
FROM {{ latest_source(source("RAW", "RAW_BALANCE_SHEET"), ['TICKER','PERIOD','YEAR']) }}
