{{
  config(
    materialized='incremental',
    unique_key=['TICKER', 'PERIOD', 'YEAR'],
    incremental_strategy='merge'
  )
}}

SELECT
  TICKER::VARCHAR(256) AS TICKER,
  PERIOD::VARCHAR(256) AS PERIOD,
  YEAR::INTEGER AS YEAR,
  REVENUE::NUMERIC(18, 4) AS REVENUE,
  COGS::NUMERIC(18, 4) AS COGS,
  GROSS_PROFIT::NUMERIC(18, 4) AS GROSS_PROFIT,
  OPERATING_EXPENSES::NUMERIC(18, 4) AS OPERATING_EXPENSES,
  OPERATING_PROFIT::NUMERIC(18, 4) AS OPERATING_PROFIT,
  FINANCIAL_INCOME::NUMERIC(18, 4) AS FINANCIAL_INCOME,
  FINANCIAL_EXPENSES::NUMERIC(18, 4) AS FINANCIAL_EXPENSES,
  NET_PROFIT_AFTER_TAX::NUMERIC(18, 4) AS NET_PROFIT_AFTER_TAX,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_INCOME_STATEMENT') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
