{{
  config(
    materialized='incremental',
    unique_key='EVENT_ID',
    incremental_strategy='merge'
  )
}}

SELECT
  EVENT_ID::VARCHAR(256) AS EVENT_ID,
  TICKER::VARCHAR(256) AS TICKER,
  EVENT_TYPE::VARCHAR(256) AS EVENT_TYPE,
  EX_RIGHT_DATE::DATE AS EX_RIGHT_DATE,
  RECORD_DATE::DATE AS RECORD_DATE,
  EVENT_DETAILS::VARCHAR(256) AS EVENT_DETAILS,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_CORPORATE_EVENTS') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
