{{
  config(
    materialized='incremental',
    unique_key='REPORT_ID',
    incremental_strategy='merge'
  )
}}

SELECT
  REPORT_ID::VARCHAR(256) AS REPORT_ID,
  TICKER::VARCHAR(256) AS TICKER,
  BROKERAGE_FIRM::VARCHAR(256) AS BROKERAGE_FIRM,
  PUBLISH_DATE::DATE AS PUBLISH_DATE,
  RECOMMENDATION::VARCHAR(256) AS RECOMMENDATION,
  TARGET_PRICE::NUMERIC(18, 4) AS TARGET_PRICE,
  REPORT_PDF_URL::VARCHAR(256) AS REPORT_PDF_URL,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_ANALYST_REPORTS') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
