{{
  config(
    materialized='incremental',
    unique_key='TRANSACTION_ID',
    incremental_strategy='merge'
  )
}}

SELECT
  TRANSACTION_ID::VARCHAR(256) AS TRANSACTION_ID,
  TICKER::VARCHAR(256) AS TICKER,
  INSIDER_NAME::VARCHAR(256) AS INSIDER_NAME,
  POSITION::VARCHAR(256) AS POSITION,
  ACTION::VARCHAR(256) AS ACTION,
  REGISTERED_VOL::NUMERIC(18, 4) AS REGISTERED_VOL,
  EXECUTED_VOL::NUMERIC(18, 4) AS EXECUTED_VOL,
  DATE_START::DATE AS DATE_START,
  DATE_END::DATE AS DATE_END,
  BATCH_DATE::DATE AS BATCH_DATE,
  _CONATA_SOURCE::VARCHAR(256) AS _CONATA_SOURCE,
  _CONATA_SOURCE_ROW_NUMBER::INTEGER AS _CONATA_SOURCE_ROW_NUMBER,
  _CONATA_PARTITION_KEY::VARCHAR(256) AS _CONATA_PARTITION_KEY,
  _CONATA_LOADED_AT::TIMESTAMP AS _CONATA_LOADED_AT
FROM {{ source('RAW', 'RAW_INSIDER_TRANSACTIONS') }}
{% if is_incremental() %}
  -- Lọc theo partition key khi chạy incremental
  WHERE _CONATA_PARTITION_KEY = '{{ var("partition_key") }}'
{% endif %}
