{{
  config(
    materialized='table',
    unique_key=['TICKER', 'TRADING_DATE']
  )
}}

-- Wide flat table for ML model consumption.
-- Built by LEFT JOINing all sub-marts on TICKER + TRADING_DATE.
-- Label columns (label_*) are computed from future returns — use ONLY as targets,
-- never as input features (data leakage risk).

WITH BASE AS (
  -- Stock price EOD is the anchor: every ticker/date pair with a closing price
  SELECT
    TICKER,
    TRADING_DATE,
    CLOSE,
    ADJUSTED_CLOSE,
    -- Future return labels using LEAD window functions
    LEAD(ADJUSTED_CLOSE, 5) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_NEXT_5D,
    LEAD(ADJUSTED_CLOSE, 20) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_NEXT_20D,
    -- Max close in next 10 days (for drawdown label)
    MAX(ADJUSTED_CLOSE) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 1 FOLLOWING AND 10 FOLLOWING
    ) AS MAX_CLOSE_NEXT_10D
  FROM {{ ref('STG_STOCK_PRICE_EOD') }}
)

SELECT
  B.TICKER::VARCHAR(256) AS TICKER,
  B.TRADING_DATE::DATE AS TRADING_DATE,

  -- ── Market Momentum features ─────────────────────────────────────────────
  MOM.PRICE_MOMENTUM_1M,
  MOM.PRICE_MOMENTUM_3M,
  MOM.VOLATILITY_30D,
  MOM.RELATIVE_STRENGTH_VS_VNINDEX,
  MOM.MOVING_AVERAGE_20D,
  MOM.MOVING_AVERAGE_50D,
  MOM.MOVING_AVERAGE_200D,

  -- ── Fundamental features ─────────────────────────────────────────────────
  FUN.REVENUE_GROWTH_YOY,
  FUN.NET_PROFIT_GROWTH_YOY,
  FUN.GROSS_MARGIN,
  FUN.NET_MARGIN,
  FUN.OPERATING_MARGIN,
  FUN.ROE,
  FUN.ROA,
  FUN.ASSET_GROWTH_YOY,
  FUN.DEBT_TO_EQUITY,
  FUN.CURRENT_RATIO,
  FUN.CASH_TO_ASSETS,
  FUN.EQUITY_MULTIPLIER,
  FUN.PE_RATIO,
  FUN.PB_RATIO,
  FUN.OPERATING_CASH_FLOW_TO_NET_INCOME,
  FUN.FREE_CASH_FLOW,
  FUN.CASH_FLOW_TO_DEBT,

  -- ── Sentiment features ───────────────────────────────────────────────────
  SNT.NEWS_COUNT,
  SNT.DAILY_NEWS_SENTIMENT_SCORE,
  SNT.SENTIMENT_MOMENTUM_7D,
  SNT.NEWS_VELOCITY,
  SNT.ANALYST_REPORT_COUNT,
  SNT.ANALYST_BUY_COUNT,
  SNT.AVG_ANALYST_TARGET_PRICE,
  SNT.CORPORATE_EVENT_COUNT,
  SNT.DIVIDEND_EVENT_COUNT,

  -- ── Macro & commodities features ─────────────────────────────────────────
  MAC.FED_RATE,
  MAC.TREASURY_10Y,
  MAC.TREASURY_5Y,
  MAC.REAL_INTEREST_RATE,
  MAC.USD_VND_RATE,
  MAC.EXCHANGE_RATE_VOLATILITY_30D,
  MAC.CPI_VALUE,
  MAC.BRENT_CRUDE_PRICE,
  MAC.WTI_PRICE,
  MAC.GOLD_PRICE,
  MAC.STEEL_HRC_PRICE,
  MAC.GASOLINE_SINGAPORE_PRICE,
  MAC.BALTIC_DIRTY_TANKER_INDEX,
  MAC.BRENT_PRICE_MOMENTUM_1M,
  MAC.CRACK_SPREAD_PROXY,

  -- ── Insider & flow features ──────────────────────────────────────────────
  FLW.FOREIGN_BUY_RATIO_10D,
  FLW.NET_FOREIGN_FLOW_1M,
  FLW.NET_FOREIGN_FLOW_MOMENTUM_1M,
  FLW.PROP_TRADING_NET_VAL_5D,
  FLW.PROP_VS_FOREIGN_CORRELATION_10D,


  -- ── Target labels (use ONLY as ML targets, never as input features) ──────
  -- label_next_5d_return: return after 5 trading days
  CASE
    WHEN B.ADJUSTED_CLOSE > 0 AND B.CLOSE_NEXT_5D IS NOT NULL
      THEN (B.CLOSE_NEXT_5D / B.ADJUSTED_CLOSE) - 1
  END::NUMERIC(18, 6) AS LABEL_NEXT_5D_RETURN,
  -- label_next_20d_return: return after 20 trading days (~1 month)
  CASE
    WHEN B.ADJUSTED_CLOSE > 0 AND B.CLOSE_NEXT_20D IS NOT NULL
      THEN (B.CLOSE_NEXT_20D / B.ADJUSTED_CLOSE) - 1
  END::NUMERIC(18, 6) AS LABEL_NEXT_20D_RETURN,
  -- label_is_uptrend_30d: 1 if 20-day forward return > 5%, else 0
  CASE
    WHEN
      B.ADJUSTED_CLOSE > 0 AND B.CLOSE_NEXT_20D IS NOT NULL
      AND (B.CLOSE_NEXT_20D / B.ADJUSTED_CLOSE) - 1 > 0.05 THEN 1
    WHEN B.CLOSE_NEXT_20D IS NOT NULL THEN 0
  END::SMALLINT AS LABEL_IS_UPTREND_30D,
  -- label_max_drawdown_next_10d: max adverse excursion over next 10 days
  CASE
    WHEN B.ADJUSTED_CLOSE > 0 AND B.MAX_CLOSE_NEXT_10D IS NOT NULL
      THEN (B.MAX_CLOSE_NEXT_10D / B.ADJUSTED_CLOSE) - 1
  END::NUMERIC(18, 6) AS LABEL_MAX_DRAWDOWN_NEXT_10D,

  -- ── Metadata ─────────────────────────────────────────────────────────────
  {{ datacore_common_metadata() }}

FROM BASE AS B
LEFT JOIN {{ ref('MART_STOCK_MARKET_MOMENTUM') }} AS MOM
  ON
    B.TICKER = MOM.TICKER
    AND B.TRADING_DATE = MOM.TRADING_DATE
LEFT JOIN {{ ref('MART_STOCK_FUNDAMENTAL_METRICS') }} AS FUN
  ON
    B.TICKER = FUN.TICKER
    AND B.TRADING_DATE = FUN.TRADING_DATE
LEFT JOIN {{ ref('MART_STOCK_SENTIMENT_SCORES') }} AS SNT
  ON
    B.TICKER = SNT.TICKER
    AND B.TRADING_DATE = SNT.DATE
LEFT JOIN {{ ref('MART_MACRO_COMMODITIES_SIGNALS') }} AS MAC
  ON
    B.TRADING_DATE = MAC.DATE
LEFT JOIN {{ ref('MART_INSIDER_PROPRIETARY_FLOWS') }} AS FLW
  ON
    B.TICKER = FLW.TICKER
    AND B.TRADING_DATE = FLW.TRADING_DATE
