{{
  config(
    materialized='table',
    unique_key=['TICKER', 'DATE']
  )
}}

-- Latest quarterly snapshot per ticker from each fundamental table.
-- Joined with daily FINANCIAL_RATIOS (market cap, shares outstanding) so that
-- the output granularity is Ticker + Date (daily), with quarterly data forward-filled.

WITH INCOME_WITH_YOY AS (
  SELECT
    TICKER,
    PERIOD,
    YEAR,
    REVENUE,
    GROSS_PROFIT,
    OPERATING_PROFIT,
    NET_PROFIT_AFTER_TAX,
    -- YoY comparison: lag by 4 quarters
    LAG(REVENUE, 4) OVER (PARTITION BY TICKER ORDER BY YEAR, PERIOD) AS REVENUE_YOY,
    LAG(NET_PROFIT_AFTER_TAX, 4) OVER (PARTITION BY TICKER ORDER BY YEAR, PERIOD) AS NET_PROFIT_YOY
  FROM {{ ref('STG_INCOME_STATEMENT') }}
),

INCOME_LATEST AS (
  SELECT
    TICKER,
    REVENUE,
    GROSS_PROFIT,
    OPERATING_PROFIT,
    NET_PROFIT_AFTER_TAX,
    REVENUE_YOY,
    NET_PROFIT_YOY,
    ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY YEAR DESC, PERIOD DESC) AS RN
  FROM INCOME_WITH_YOY
  QUALIFY RN = 1
),

BALANCE_WITH_YOY AS (
  SELECT
    TICKER,
    TOTAL_ASSETS,
    CURRENT_ASSETS,
    CASH,
    TOTAL_LIABILITIES,
    SHORT_TERM_DEBT,
    LONG_TERM_DEBT,
    EQUITY,
    LAG(TOTAL_ASSETS, 4) OVER (PARTITION BY TICKER ORDER BY YEAR, PERIOD) AS TOTAL_ASSETS_YOY,
    ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY YEAR DESC, PERIOD DESC) AS RN
  FROM {{ ref('STG_BALANCE_SHEET') }}
  QUALIFY RN = 1
),

CASHFLOW_LATEST AS (
  SELECT
    TICKER,
    CFO,
    CAPEX,
    ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY YEAR DESC, PERIOD DESC) AS RN
  FROM {{ ref('STG_CASHFLOW_STATEMENT') }}
  QUALIFY RN = 1
)

SELECT
  R.TICKER::VARCHAR(256) AS TICKER,
  R.DATE::DATE AS DATE,
  -- Revenue & profit growth (YoY, quarterly)
  CASE
    WHEN I.REVENUE_YOY > 0
      THEN ((I.REVENUE / I.REVENUE_YOY) - 1)
  END::NUMERIC(18, 6) AS REVENUE_GROWTH_YOY,
  CASE
    WHEN I.NET_PROFIT_YOY > 0
      THEN ((I.NET_PROFIT_AFTER_TAX / I.NET_PROFIT_YOY) - 1)
  END::NUMERIC(18, 6) AS NET_PROFIT_GROWTH_YOY,
  -- Margin ratios
  CASE
    WHEN I.REVENUE != 0
      THEN I.GROSS_PROFIT / I.REVENUE
  END::NUMERIC(18, 6) AS GROSS_MARGIN,
  CASE
    WHEN I.REVENUE != 0
      THEN I.NET_PROFIT_AFTER_TAX / I.REVENUE
  END::NUMERIC(18, 6) AS NET_MARGIN,
  CASE
    WHEN I.REVENUE != 0
      THEN I.OPERATING_PROFIT / I.REVENUE
  END::NUMERIC(18, 6) AS OPERATING_MARGIN,
  -- Return on equity / assets
  CASE
    WHEN B.EQUITY != 0
      THEN I.NET_PROFIT_AFTER_TAX / B.EQUITY
  END::NUMERIC(18, 6) AS ROE,
  CASE
    WHEN B.TOTAL_ASSETS != 0
      THEN I.NET_PROFIT_AFTER_TAX / B.TOTAL_ASSETS
  END::NUMERIC(18, 6) AS ROA,
  -- Balance sheet ratios
  CASE
    WHEN B.TOTAL_ASSETS_YOY > 0
      THEN ((B.TOTAL_ASSETS / B.TOTAL_ASSETS_YOY) - 1)
  END::NUMERIC(18, 6) AS ASSET_GROWTH_YOY,
  CASE
    WHEN B.EQUITY != 0
      THEN (B.SHORT_TERM_DEBT + B.LONG_TERM_DEBT) / B.EQUITY
  END::NUMERIC(18, 6) AS DEBT_TO_EQUITY,
  CASE
    WHEN B.TOTAL_LIABILITIES != 0
      THEN B.CURRENT_ASSETS / B.TOTAL_LIABILITIES
  END::NUMERIC(18, 6) AS CURRENT_RATIO,
  CASE
    WHEN B.TOTAL_ASSETS != 0
      THEN B.CASH / B.TOTAL_ASSETS
  END::NUMERIC(18, 6) AS CASH_TO_ASSETS,
  CASE
    WHEN B.EQUITY != 0
      THEN B.TOTAL_ASSETS / B.EQUITY
  END::NUMERIC(18, 6) AS EQUITY_MULTIPLIER,
  -- Valuation multiples (market cap from daily data, profit from quarterly)
  CASE
    WHEN I.NET_PROFIT_AFTER_TAX != 0
      THEN R.MARKET_CAP / I.NET_PROFIT_AFTER_TAX
  END::NUMERIC(18, 4) AS PE_RATIO,
  CASE
    WHEN B.EQUITY != 0
      THEN R.MARKET_CAP / B.EQUITY
  END::NUMERIC(18, 4) AS PB_RATIO,
  -- Cash flow ratios
  CASE
    WHEN I.NET_PROFIT_AFTER_TAX != 0
      THEN CF.CFO / I.NET_PROFIT_AFTER_TAX
  END::NUMERIC(18, 6) AS OPERATING_CASH_FLOW_TO_NET_INCOME,
  (CF.CFO - CF.CAPEX)::NUMERIC(18, 4) AS FREE_CASH_FLOW,
  CASE
    WHEN (B.SHORT_TERM_DEBT + B.LONG_TERM_DEBT) != 0
      THEN CF.CFO / (B.SHORT_TERM_DEBT + B.LONG_TERM_DEBT)
  END::NUMERIC(18, 6) AS CASH_FLOW_TO_DEBT,
  {{ datacore_common_metadata() }}
FROM {{ ref('STG_FINANCIAL_RATIOS') }} AS R
LEFT JOIN INCOME_LATEST AS I
  ON
    R.TICKER = I.TICKER
LEFT JOIN BALANCE_WITH_YOY AS B
  ON
    R.TICKER = B.TICKER
LEFT JOIN CASHFLOW_LATEST AS CF
  ON
    R.TICKER = CF.TICKER
