{{
  config(
    materialized='table',
    unique_key=['TICKER', 'TRADING_DATE']
  )
}}

-- Aggregates insider transactions, proprietary desk activity, and foreign flow
-- signals at the Ticker + Date granularity.
-- Insider transactions span a date range (DATE_START to DATE_END); they are
-- attributed to DATE_START for simplicity.

WITH FOREIGN_FLOW_BASE AS (
  SELECT
    TICKER,
    TRADING_DATE,
    BUY_VOL,
    SELL_VOL,
    BUY_VAL,
    SELL_VAL,
    NET_VAL,
    -- 10-day rolling foreign buy ratio
    SUM(BUY_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS BUY_VAL_10D,
    SUM(BUY_VAL + SELL_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS TOTAL_TRADING_VAL_10D,
    -- 1-month (20-day) net foreign flow for momentum
    SUM(NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS NET_FOREIGN_VAL_1M
  FROM {{ ref('STG_FOREIGN_TRADING') }}
),

FOREIGN_FLOW AS (
  SELECT
    *,
    LAG(NET_FOREIGN_VAL_1M, 20) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
    ) AS NET_FOREIGN_VAL_1M_PREV
  FROM FOREIGN_FLOW_BASE
),

PROPRIETARY_FLOW AS (
  SELECT
    TICKER,
    TRADING_DATE,
    NET_VAL AS PROP_NET_VAL,
    -- 5-day rolling sum of proprietary net value
    SUM(NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
    ) AS PROP_NET_VAL_5D
  FROM {{ ref('STG_PROPRIETARY_TRADING') }}
),

-- Correlation between prop and foreign net value over 10 days
PROP_FOREIGN_JOINED AS (
  SELECT
    P.TICKER,
    P.TRADING_DATE,
    P.PROP_NET_VAL,
    F.NET_VAL AS FOREIGN_NET_VAL
  FROM PROPRIETARY_FLOW AS P
  LEFT JOIN FOREIGN_FLOW AS F
    ON
      P.TICKER = F.TICKER
      AND P.TRADING_DATE = F.TRADING_DATE
),

PROP_FOREIGN_STATS AS (
  SELECT
    TICKER,
    TRADING_DATE,
    PROP_NET_VAL::DOUBLE PRECISION AS X,
    FOREIGN_NET_VAL::DOUBLE PRECISION AS Y,
    COUNT(1) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS N,
    SUM(PROP_NET_VAL::DOUBLE PRECISION) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS SUM_X,
    SUM(FOREIGN_NET_VAL::DOUBLE PRECISION) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS SUM_Y,
    SUM(PROP_NET_VAL::DOUBLE PRECISION * PROP_NET_VAL::DOUBLE PRECISION) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS SUM_XX,
    SUM(FOREIGN_NET_VAL::DOUBLE PRECISION * FOREIGN_NET_VAL::DOUBLE PRECISION) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS SUM_YY,
    SUM(PROP_NET_VAL::DOUBLE PRECISION * FOREIGN_NET_VAL::DOUBLE PRECISION) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS SUM_XY
  FROM PROP_FOREIGN_JOINED
),

PROP_FOREIGN_CORR AS (
  SELECT
    TICKER,
    TRADING_DATE,
    CASE
      WHEN N <= 1 THEN NULL
      WHEN (N * SUM_XX - SUM_X * SUM_X) * (N * SUM_YY - SUM_Y * SUM_Y) <= 0 THEN NULL
      ELSE (N * SUM_XY - SUM_X * SUM_Y) / SQRT((N * SUM_XX - SUM_X * SUM_X) * (N * SUM_YY - SUM_Y * SUM_Y))
    END AS PROP_VS_FOREIGN_CORRELATION_10D
  FROM PROP_FOREIGN_STATS
),



SELECT
  FF.TICKER::VARCHAR(256) AS TICKER,
  FF.TRADING_DATE::DATE AS TRADING_DATE,
  -- Foreign flow signals
  CASE
    WHEN FF.TOTAL_TRADING_VAL_10D > 0
      THEN FF.BUY_VAL_10D / FF.TOTAL_TRADING_VAL_10D
  END::NUMERIC(18, 6) AS FOREIGN_BUY_RATIO_10D,
  FF.NET_FOREIGN_VAL_1M::NUMERIC(18, 4) AS NET_FOREIGN_FLOW_1M,
  -- 1-month momentum in foreign flow (current vs prior period)
  CASE
    WHEN FF.NET_FOREIGN_VAL_1M_PREV != 0
      THEN FF.NET_FOREIGN_VAL_1M / ABS(FF.NET_FOREIGN_VAL_1M_PREV) - 1
  END::NUMERIC(18, 6) AS NET_FOREIGN_FLOW_MOMENTUM_1M,
  -- Proprietary trading signals
  PF.PROP_NET_VAL_5D::NUMERIC(18, 4) AS PROP_TRADING_NET_VAL_5D,
  PFC.PROP_VS_FOREIGN_CORRELATION_10D::NUMERIC(18, 6) AS PROP_VS_FOREIGN_CORRELATION_10D,
  {{ datacore_common_metadata() }}
FROM FOREIGN_FLOW AS FF
LEFT JOIN PROPRIETARY_FLOW AS PF
  ON
    FF.TICKER = PF.TICKER
    AND FF.TRADING_DATE = PF.TRADING_DATE
LEFT JOIN PROP_FOREIGN_CORR AS PFC
  ON
    FF.TICKER = PFC.TICKER
    AND FF.TRADING_DATE = PFC.TRADING_DATE
