{{
  config(
    materialized='table',
    unique_key='DATE'
  )
}}

-- Macro & commodities signals at daily granularity (no ticker dimension).
-- Interest rates, exchange rates, and commodity prices are pivoted to columns
-- so downstream FACT_ML_FEATURE_SET can join on DATE only.

WITH INTEREST_RATES_PIVOT AS (
  -- Fed proxy (^IRX), 10Y Treasury (^TNX), 5Y Treasury (^FVX)
  SELECT
    DATE,
    MAX(CASE WHEN RATE_TYPE = '^IRX' THEN RATE_VALUE END) AS FED_RATE,
    MAX(CASE WHEN RATE_TYPE = '^TNX' THEN RATE_VALUE END) AS TREASURY_10Y,
    MAX(CASE WHEN RATE_TYPE = '^FVX' THEN RATE_VALUE END) AS TREASURY_5Y
  FROM {{ ref('STG_INTEREST_RATES') }}
  GROUP BY 1
),

USDVND AS (
  SELECT
    DATE,
    EXCHANGE_RATE AS USD_VND_RATE,
    LAG(EXCHANGE_RATE, 1) OVER (ORDER BY DATE) AS PREV_RATE
  FROM {{ ref('STG_EXCHANGE_RATES') }}
  WHERE PAIR = 'USDT/VND'
),

EXCHANGE_RATE_VOL AS (
  SELECT
    DATE,
    USD_VND_RATE,
    -- 30-day volatility of USD/VND daily return
    STDDEV(
      CASE WHEN PREV_RATE > 0 THEN (USD_VND_RATE / PREV_RATE) - 1 END
    ) OVER (
      ORDER BY DATE
      ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS EXCHANGE_RATE_VOLATILITY_30D
  FROM USDVND
),

MACRO_PIVOT AS (
  -- Forward-fill monthly/quarterly macro indicators to daily using LAST_VALUE
  -- We pivot the two key indicators: CPI (inflation) and interest rate proxy
  SELECT
    REPORT_DATE AS DATE,
    MAX(CASE WHEN INDICATOR_NAME = 'CPI' THEN VALUE END) AS CPI_VALUE,
    MAX(CASE WHEN INDICATOR_NAME = 'INTEREST_RATE' THEN VALUE END) AS POLICY_RATE
  FROM {{ ref('STG_MACRO_INDICATORS') }}
  GROUP BY 1
),

BRENT_CRUDE AS (
  SELECT
    DATE,
    PRICE AS BRENT_PRICE,
    LAG(PRICE, 30) OVER (ORDER BY DATE) AS BRENT_PRICE_30D_AGO
  FROM {{ ref('STG_COMMODITIES_PRICE') }}
  WHERE COMMODITY_NAME = 'Brent Crude'
),

COMMODITIES_PIVOT AS (
  SELECT
    DATE,
    MAX(CASE WHEN COMMODITY_NAME = 'Brent Crude' THEN PRICE END) AS BRENT_CRUDE_PRICE,
    MAX(CASE WHEN COMMODITY_NAME = 'WTI' THEN PRICE END) AS WTI_PRICE,
    MAX(CASE WHEN COMMODITY_NAME = 'Gold' THEN PRICE END) AS GOLD_PRICE,
    MAX(CASE WHEN COMMODITY_NAME = 'Steel HRC' THEN PRICE END) AS STEEL_HRC_PRICE,
    MAX(CASE
      WHEN
        COMMODITY_NAME LIKE '%Gasoline%'
        AND COMMODITY_NAME LIKE '%Singapore%' THEN PRICE
    END) AS GASOLINE_SINGAPORE_PRICE,
    MAX(CASE
      WHEN
        COMMODITY_NAME LIKE '%Baltic%'
        AND COMMODITY_NAME LIKE '%Dirty%' THEN PRICE
    END) AS BALTIC_DIRTY_TANKER_INDEX
  FROM {{ ref('STG_COMMODITIES_PRICE') }}
  GROUP BY 1
),

-- Use brent crude date spine as the anchor (most complete daily commodity series)
DATE_SPINE AS (
  SELECT DISTINCT DATE FROM {{ ref('STG_COMMODITIES_PRICE') }}
)

SELECT
  DS.DATE::DATE AS DATE,
  -- Interest rates
  IR.FED_RATE::NUMERIC(18, 4) AS FED_RATE,
  IR.TREASURY_10Y::NUMERIC(18, 4) AS TREASURY_10Y,
  IR.TREASURY_5Y::NUMERIC(18, 4) AS TREASURY_5Y,
  -- Real interest rate = nominal (Fed) minus CPI inflation
  CASE
    WHEN IR.FED_RATE IS NOT NULL AND M.CPI_VALUE IS NOT NULL
      THEN IR.FED_RATE - M.CPI_VALUE
  END::NUMERIC(18, 4) AS REAL_INTEREST_RATE,
  -- Exchange rate signals
  ER.USD_VND_RATE::NUMERIC(18, 4) AS USD_VND_RATE,
  ER.EXCHANGE_RATE_VOLATILITY_30D::NUMERIC(18, 6) AS EXCHANGE_RATE_VOLATILITY_30D,
  -- Macro indicators
  M.CPI_VALUE::NUMERIC(18, 4) AS CPI_VALUE,
  M.POLICY_RATE::NUMERIC(18, 4) AS POLICY_RATE,
  -- Commodity prices
  CP.BRENT_CRUDE_PRICE::NUMERIC(18, 4) AS BRENT_CRUDE_PRICE,
  CP.WTI_PRICE::NUMERIC(18, 4) AS WTI_PRICE,
  CP.GOLD_PRICE::NUMERIC(18, 4) AS GOLD_PRICE,
  CP.STEEL_HRC_PRICE::NUMERIC(18, 4) AS STEEL_HRC_PRICE,
  CP.GASOLINE_SINGAPORE_PRICE::NUMERIC(18, 4) AS GASOLINE_SINGAPORE_PRICE,
  CP.BALTIC_DIRTY_TANKER_INDEX::NUMERIC(18, 4) AS BALTIC_DIRTY_TANKER_INDEX,
  -- Brent momentum (30-day price change %)
  CASE
    WHEN B.BRENT_PRICE_30D_AGO > 0
      THEN (B.BRENT_PRICE / B.BRENT_PRICE_30D_AGO) - 1
  END::NUMERIC(18, 6) AS BRENT_PRICE_MOMENTUM_1M,
  -- Crack spread proxy: gasoline Singapore minus Brent
  CASE
    WHEN CP.GASOLINE_SINGAPORE_PRICE IS NOT NULL AND CP.BRENT_CRUDE_PRICE IS NOT NULL
      THEN CP.GASOLINE_SINGAPORE_PRICE - CP.BRENT_CRUDE_PRICE
  END::NUMERIC(18, 4) AS CRACK_SPREAD_PROXY,
  {{ datacore_common_metadata() }}
FROM DATE_SPINE AS DS
LEFT JOIN INTEREST_RATES_PIVOT AS IR
  ON
    DS.DATE = IR.DATE
LEFT JOIN EXCHANGE_RATE_VOL AS ER
  ON
    DS.DATE = ER.DATE
LEFT JOIN MACRO_PIVOT AS M
  ON
    DS.DATE = M.DATE
LEFT JOIN COMMODITIES_PIVOT AS CP
  ON
    DS.DATE = CP.DATE
LEFT JOIN BRENT_CRUDE AS B
  ON
    DS.DATE = B.DATE
