{{
  config(
    materialized='table',
    unique_key=['TICKER', 'TRADING_DATE']
  )
}}

-- Aggregates insider transactions, proprietary desk activity, and foreign flow
-- signals at the Ticker + Date granularity.
-- Insider transactions span a date range (DATE_START to DATE_END); they are
-- attributed to DATE_START for simplicity.

WITH FOREIGN_FLOW AS (
  SELECT
    TICKER,
    TRADING_DATE,
    BUY_VOL,
    SELL_VOL,
    BUY_VAL,
    SELL_VAL,
    NET_VAL,
    -- 10-day rolling foreign buy ratio
    SUM(BUY_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS BUY_VAL_10D,
    SUM(BUY_VAL + SELL_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS TOTAL_TRADING_VAL_10D,
    -- 1-month (20-day) net foreign flow for momentum
    SUM(NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS NET_FOREIGN_VAL_1M,
    LAG(SUM(NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ), 20) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS NET_FOREIGN_VAL_1M_PREV
  FROM {{ ref('STG_FOREIGN_TRADING') }}
),

PROPRIETARY_FLOW AS (
  SELECT
    TICKER,
    TRADING_DATE,
    NET_VAL AS PROP_NET_VAL,
    BUY_VOL AS PROP_BUY_VOL,
    SELL_VOL AS PROP_SELL_VOL,
    -- 5-day rolling sum of proprietary net value
    SUM(NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
    ) AS PROP_NET_VAL_5D
  FROM {{ ref('STG_PROPRIETARY_TRADING') }}
),

-- Correlation between prop and foreign net value over 10 days
PROP_FOREIGN_JOINED AS (
  SELECT
    P.TICKER,
    P.TRADING_DATE,
    P.PROP_NET_VAL,
    F.NET_VAL AS FOREIGN_NET_VAL
  FROM PROPRIETARY_FLOW AS P
  LEFT JOIN FOREIGN_FLOW AS F
    ON
      P.TICKER = F.TICKER
      AND P.TRADING_DATE = F.TRADING_DATE
),

PROP_FOREIGN_CORR AS (
  SELECT
    TICKER,
    TRADING_DATE,
    CORR(PROP_NET_VAL, FOREIGN_NET_VAL) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ) AS PROP_VS_FOREIGN_CORRELATION_10D
  FROM PROP_FOREIGN_JOINED
),

INSIDER_SIGNALS AS (
  -- Aggregate insider transactions by ticker and announcement date
  SELECT
    TICKER,
    DATE_START AS TRADING_DATE,
    SUM(CASE WHEN UPPER(ACTION) = 'BUY' THEN EXECUTED_VOL ELSE 0 END) AS INSIDER_BUY_VOL,
    SUM(CASE WHEN UPPER(ACTION) = 'SELL' THEN EXECUTED_VOL ELSE 0 END) AS INSIDER_SELL_VOL,
    SUM(EXECUTED_VOL) AS INSIDER_TOTAL_VOL,
    -- -1 net sell, +1 net buy, 0 neutral
    SIGN(
      SUM(CASE WHEN UPPER(ACTION) = 'BUY' THEN EXECUTED_VOL ELSE 0 END)
      - SUM(CASE WHEN UPPER(ACTION) = 'SELL' THEN EXECUTED_VOL ELSE 0 END)
    ) AS INSIDER_SENTIMENT_SIGNAL
  FROM {{ ref('STG_INSIDER_TRANSACTIONS') }}
  GROUP BY 1, 2
)

SELECT
  FF.TICKER::VARCHAR(256) AS TICKER,
  FF.TRADING_DATE::DATE AS TRADING_DATE,
  -- Foreign flow signals
  CASE
    WHEN FF.TOTAL_TRADING_VAL_10D > 0
      THEN FF.BUY_VAL_10D / FF.TOTAL_TRADING_VAL_10D
  END::NUMERIC(18, 6) AS FOREIGN_BUY_RATIO_10D,
  FF.NET_FOREIGN_VAL_1M::NUMERIC(18, 4) AS NET_FOREIGN_FLOW_1M,
  -- 1-month momentum in foreign flow (current vs prior period)
  CASE
    WHEN FF.NET_FOREIGN_VAL_1M_PREV != 0
      THEN FF.NET_FOREIGN_VAL_1M / ABS(FF.NET_FOREIGN_VAL_1M_PREV) - 1
  END::NUMERIC(18, 6) AS NET_FOREIGN_FLOW_MOMENTUM_1M,
  -- Proprietary trading signals
  PF.PROP_NET_VAL_5D::NUMERIC(18, 4) AS PROP_TRADING_NET_VAL_5D,
  PFC.PROP_VS_FOREIGN_CORRELATION_10D::NUMERIC(18, 6) AS PROP_VS_FOREIGN_CORRELATION_10D,
  -- Insider trading signals (NULL on days with no transactions)
  INS.INSIDER_SENTIMENT_SIGNAL::SMALLINT AS INSIDER_SENTIMENT_SIGNAL,
  CASE
    WHEN INS.INSIDER_TOTAL_VOL > 0
      THEN INS.INSIDER_BUY_VOL / INS.INSIDER_TOTAL_VOL
  END::NUMERIC(18, 6) AS INSIDER_BUY_VOLUME_RATIO,
  {{ datacore_common_metadata() }}
FROM FOREIGN_FLOW AS FF
LEFT JOIN PROPRIETARY_FLOW AS PF
  ON
    FF.TICKER = PF.TICKER
    AND FF.TRADING_DATE = PF.TRADING_DATE
LEFT JOIN PROP_FOREIGN_CORR AS PFC
  ON
    FF.TICKER = PFC.TICKER
    AND FF.TRADING_DATE = PFC.TRADING_DATE
LEFT JOIN INSIDER_SIGNALS AS INS
  ON
    FF.TICKER = INS.TICKER
    AND FF.TRADING_DATE = INS.TRADING_DATE
