{{
  config(
    materialized='table',
    unique_key=['TICKER', 'TRADING_DATE']
  )
}}

WITH STOCK_PRICES AS (
  SELECT
    TICKER,
    TRADING_DATE,
    CLOSE,
    ADJUSTED_CLOSE,
    -- Lag prices for momentum & moving average calculations
    LAG(ADJUSTED_CLOSE, 1) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS PREV_CLOSE,
    LAG(ADJUSTED_CLOSE, 20) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_20D_AGO,
    LAG(ADJUSTED_CLOSE, 30) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_30D_AGO,
    LAG(ADJUSTED_CLOSE, 50) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_50D_AGO,
    LAG(ADJUSTED_CLOSE, 90) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_90D_AGO,
    LAG(ADJUSTED_CLOSE, 200) OVER (PARTITION BY TICKER ORDER BY TRADING_DATE) AS CLOSE_200D_AGO
  FROM {{ ref('STG_STOCK_PRICE_EOD') }}
),

DAILY_RETURNS AS (
  SELECT
    TICKER,
    TRADING_DATE,
    CLOSE,
    ADJUSTED_CLOSE,
    CLOSE_20D_AGO,
    CLOSE_30D_AGO,
    CLOSE_50D_AGO,
    CLOSE_90D_AGO,
    CLOSE_200D_AGO,
    -- Daily log return for volatility calculation
    CASE
      WHEN PREV_CLOSE > 0 THEN (ADJUSTED_CLOSE / PREV_CLOSE) - 1
    END AS DAILY_RETURN
  FROM STOCK_PRICES
),

STOCK_METRICS AS (
  SELECT
    TICKER,
    TRADING_DATE,
    CLOSE,
    ADJUSTED_CLOSE,
    -- Price momentum
    CASE WHEN CLOSE_30D_AGO > 0 THEN (ADJUSTED_CLOSE / CLOSE_30D_AGO) - 1 END AS PRICE_MOMENTUM_1M,
    CASE WHEN CLOSE_90D_AGO > 0 THEN (ADJUSTED_CLOSE / CLOSE_90D_AGO) - 1 END AS PRICE_MOMENTUM_3M,
    -- Rolling moving averages
    AVG(ADJUSTED_CLOSE) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVERAGE_20D,
    AVG(ADJUSTED_CLOSE) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 49 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVERAGE_50D,
    AVG(ADJUSTED_CLOSE) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 199 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVERAGE_200D,
    -- 30-day realised volatility (std dev of daily returns)
    STDDEV(DAILY_RETURN) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS VOLATILITY_30D,
    -- Average daily return over 20 trading days (~1 month)
    AVG(DAILY_RETURN) OVER (
      PARTITION BY TICKER ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS AVG_RETURN_1M
  FROM DAILY_RETURNS
),

VNINDEX_DAILY AS (
  SELECT
    TRADING_DATE,
    CLOSE,
    LAG(CLOSE, 1) OVER (ORDER BY TRADING_DATE) AS PREV_CLOSE
  FROM {{ ref('STG_INDEX_PRICE_EOD') }}
  WHERE INDEX_NAME = 'VNINDEX'
),

VNINDEX_RETURNS AS (
  SELECT
    TRADING_DATE,
    CASE WHEN PREV_CLOSE > 0 THEN (CLOSE / PREV_CLOSE) - 1 END AS VNINDEX_DAILY_RETURN
  FROM VNINDEX_DAILY
),

VNINDEX_1M AS (
  SELECT
    TRADING_DATE,
    -- Average daily VNINDEX return over 20 trading days
    AVG(VNINDEX_DAILY_RETURN) OVER (
      ORDER BY TRADING_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ) AS VNINDEX_RETURN_1M
  FROM VNINDEX_RETURNS
)

SELECT
  S.TICKER::VARCHAR(256) AS TICKER,
  S.TRADING_DATE::DATE AS TRADING_DATE,
  S.PRICE_MOMENTUM_1M::NUMERIC(18, 6) AS PRICE_MOMENTUM_1M,
  S.PRICE_MOMENTUM_3M::NUMERIC(18, 6) AS PRICE_MOMENTUM_3M,
  S.VOLATILITY_30D::NUMERIC(18, 6) AS VOLATILITY_30D,
  -- Relative strength = stock monthly return minus VNINDEX monthly return
  (S.AVG_RETURN_1M - V.VNINDEX_RETURN_1M)::NUMERIC(18, 6) AS RELATIVE_STRENGTH_VS_VNINDEX,
  S.MOVING_AVERAGE_20D::NUMERIC(18, 4) AS MOVING_AVERAGE_20D,
  S.MOVING_AVERAGE_50D::NUMERIC(18, 4) AS MOVING_AVERAGE_50D,
  S.MOVING_AVERAGE_200D::NUMERIC(18, 4) AS MOVING_AVERAGE_200D,
  {{ datacore_common_metadata() }}
FROM STOCK_METRICS AS S
LEFT JOIN VNINDEX_1M AS V
  ON
    S.TRADING_DATE = V.TRADING_DATE
