name: "transform"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.8.0", "<2.0.0"]

profile: "transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  send_anonymous_usage_stats: false

clean-targets:
  - "target"
  - "dbt_packages"

query-comment:
  comment: >
    Executed by FinOps Data Stack.
    {% set comment_dict = {} -%}
    {%- if node is not none -%}
      {%- do comment_dict.update(node_id=node.unique_id) -%}
    {% else %}
      {%- do comment_dict.update(connection_name=connection_name) -%}
    {%- endif -%}
    {{ tojson(comment_dict) }}

vars:
  partition_key: ""
  batch_date: ""
  dagster_job_name: ""

models:
  +persist_docs:
    relation: true
    columns: true
  transform:
    +pre-hook: |
      {{ add_query_tag() }}
    +tmp_relation_type: table
    STG:
      +schema: "{{ env_var('REDSHIFT_STAGING_SCHEMA', 'DEV_STAGING') }}"
      +group: STG
      +tags: ['staging']
    MART:
      +schema: "{{ env_var('REDSHIFT_MART_SCHEMA', 'DEV_MART') }}"
      +group: MART
      +tags: ['mart']
