name: "transform"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.8.0", "<2.0.0"]

profile: "transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  send_anonymous_usage_stats: false

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  partition_key: ""
  batch_date: ""
  dagster_job_name: ""

models:
  transform:
    +tmp_relation_type: table
    STG:
      +schema: "{{ env_var('REDSHIFT_STAGING_SCHEMA', 'staging') }}"
      +group: STG
      +tags: ['staging']
    MART:
      +schema: "{{ env_var('REDSHIFT_MART_SCHEMA', 'mart') }}"
      +group: MART
      +tags: ['mart']
