transform:
  target: dev
  outputs:
    dev:
      type: "{{ env_var('DBT_TYPE', 'redshift') }}"
      host: "{{ env_var('REDSHIFT_HOST', 'localhost') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER', 'awsuser') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD', '') }}"
      dbname: "{{ env_var('REDSHIFT_DATABASE', '') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA_RAW', 'raw') }}"
      threads: 4
      connect_retries: 3
      reuse_connections: true
      client_session_keep_alive: true
    no_snowflake_access:
      type: redshift
      host: localhost
      port: 5439
      user: test
      password: ''
      dbname: test
      schema: dev_mart
      threads: 1
